name: Test

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Clang-format
        run: |
          find src/ extras/tests/ -name '*.[hc]' -o -name '*.[hc]pp' | xargs clang-format -i --verbose --style=file
          git diff --exit-code

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
      - name: Build
        run: cmake --build .
      - name: Test
        run: ctest --output-on-failure -C Debug .
